var SystemApp={
    'os.desk':{
        name:'系统桌面'
    },
    'os.lock':{
        name:'系统锁屏'
    },
    'os.time':{
        name:'系统时间服务'
    },
    'os.web.h5':{
        name:'HTML5中枢服务'
    },
    'os.web.browser':{
        name:'浏览器中枢服务'
    },
    'os.start':{
        name:'开机引导'
    },
}
var BuiltInApp={
    'com.android.browser':{
        name:'浏览器',
        icon:'@image/ssbrowser.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html',
        pin:true
    },
    'com.android.settings':{
        name:'设置',
        icon:'@image/settings.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.calculator':{
        name:'计算器',
        icon:'@image/sscalculator.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.calender':{
        name:'日历',
        icon:'@image/sscalender.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.store':{
        name:'应用商店',
        icon:'@image/ssapps.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.phone':{
        name:'电话',
        icon:'@image/ssphone.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html',
        pin:true
    },
    'com.android.clock':{
        name:'时钟',
        icon:'@image/ssclock.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.notes':{
        name:'便签',
        icon:'@image/ssnotes.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.music':{
        name:'音乐',
        icon:'@image/ssmusic.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.contacts':{
        name:'联系人',
        icon:'@image/contacts.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html',
        pin:true
    },
    'https://github.com/smalla001/android-online':{
        name:'Github',
        icon:'../img/github.png',
        pin:true
    }
};