var AppList={
    'com.android.brower':{
        name:'浏览器',
        icon:'../img/ssbrowser.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html',
        pin:true
    },
    'com.android.settings':{
        name:'设置',
        icon:'../img/settings.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html',
        pin:true
    },
    'com.android.calculator':{
        name:'计算器',
        icon:'../img/sscalculator.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.calender':{
        name:'日历',
        icon:'../img/sscalender.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.store':{
        name:'应用商店',
        icon:'../img/ssapps.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.phone':{
        name:'电话',
        icon:'../img/ssphone.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html',
        pin:true
    },
    'com.android.clock':{
        name:'时钟',
        icon:'../img/ssclock.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.notes':{
        name:'便签',
        icon:'../img/ssnotes.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.music':{
        name:'音乐',
        icon:'../img/ssmusic.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.android.contacts':{
        name:'联系人',
        icon:'../img/contacts.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.google.chrome':{
        name:'Chrome',
        icon:'../img/chrome.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'com.baidu.search':{
        name:'百度',
        icon:'../img/baidu.png',
        version:'1.0.0',
        versionId:1,
        start:'index.html'
    },
    'https://github.com/smalla001':{
        name:'Github',
        icon:'../img/github.png',
        pin:true
    },
};